
server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:\Users\Cesar\Documents\cesar\cursos\Spring\springmicro\DemoApp\confsvr\src\main\resources\config\licensingservice

